stages:
 - testing

before_script:
  - go get -u golang.org/x/lint/golint
  - go get -insecure all

Testing:
  stage: testing
  image: golangci/golangci-lint
  script:
    - golint -set_exit_status ./...
    - golangci-lint run
    - go test -cover ./... -coverprofile=cover.out
    - go tool cover -func "cover.out"
