stages:
 - testing

Testing:
  stage: testing
  image: golangci/golangci-lint
  script:
    - go get -insecure all
    - golangci-lint run
    - go test -cover ./... -coverprofile=cover.out
    - go tool cover -func "cover.out"
